const dummyJobs = [
  {
    employer_name: "Tanisha Systems, Inc",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTnxzdwZkGIfkULLcFylqAUtVDM6wqzSlaOXe-&s=0",
    employer_website: "http://www.tanishasystems.com",
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "et0MzTUFsjQAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "React JS Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/react-js-developer-at-tanisha-systems-inc-3549902193",
    job_city: "Dallas",
    job_state: "TX",
    job_country: "US",
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react&htidocid=et0MzTUFsjQAAAAAAAAAAA%3D%3D",
    job_highlights: {
      Qualifications: [
        "Experience – 8-12 years",
        "Strong proficiency in JavaScript, including DOM manipulation and the JavaScript object model",
        "Thorough understanding of React.js and its core principles",
        "Experience with popular React.js state management workflows (such as Redux or Zustand)",
        "Experience in designing and developing Responsive React applications",
        "Familiarity with newer specifications of EcmaScript",
        "Micro app development and Micro Front end architecture exposure",
        "Familiarity with RESTful APIs and Springboot framework",
        "Knowledge of modern authorization mechanisms, such as JSON Web Token and Oauth",
        "Familiarity with modern front-end build pipelines and tools (Jenkins)",
        "Experience with common front-end development tools such as Babel, Webpack, NPM",
        "Familiarity with code versioning tools (GIT)",
        "Test automation using Test Cafe or Playwright",
        "Strong problem-solving and analytical skills",
        "Understanding of basic accessibility implementation",
      ],
    },
  },
  {
    employer_name: "Peyton Resource Group",
    employer_logo: null,
    employer_website: null,
    employer_company_type: "Staffing",
    job_publisher: "Dice",
    job_id: "KOac5Wl1HBoAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "React Developer",
    job_apply_link:
      "https://www.dice.com/job-detail/d2b459f7-2f06-4b33-9076-80ee75f8be52",
    job_city: "San Antonio",
    job_state: "TX",
    job_country: "US",
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react&htidocid=KOac5Wl1HBoAAAAAAAAAAA%3D%3D",
    job_highlights: {
      Qualifications: [
        "A Bachelor’s degree in computer science, information systems, or a related field (required)",
        "Three or more years of professional software development experience with React, TypeScript, Redux, and supporting technologies is required",
      ],
      Responsibilities: [
        "The successful candidate will perform system analysis and develop advanced programming code in addition to providing support and problem resolution for computer applications",
        "Analyze, design, and develop software that delivers clean, maintainable code within a large, highly complex, existing code base with a focus on front-end UI that is tightly coupled to data",
        "Develop web and mobile web software solutions solutions written in Typescript with a heavy focus on database and ReactJS frameworks",
        "Completes software analysis, code analysis, requirements analysis, software reviews, identification of code metrics, system risk analysis, and software reliability analysis",
        "Assist with end user training, documentation, and support",
        "Analyzes system specifications and translates system requirements to task specifications independently or in collaboration with other team members",
      ],
      Benefits: [
        "Competitive pay",
        "7% Employer-Funded retirement contribution starting day one",
        "Full insurance benefits",
        "Holidays, PTO and a paid week off in the last week of December",
      ],
    },
  },
  {
    employer_name: "Wells Fargo",
    employer_logo:
      "https://www.wellsfargo.com/assets/images/logos/wellsfargo/logo_974x1050.png",
    employer_website: "http://www.wellsfargo.com",
    employer_company_type: "Finance",
    job_publisher: "Wellsfargojobs.com",
    job_id: "COD1AgHDudYAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Principal Java Engineer",
    job_apply_link:
      "https://www.wellsfargojobs.com/fr/jobs/r-254147/principal-java-engineer/",
    job_city: "Chandler",
    job_state: "AZ",
    job_country: "US",
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=java&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=java&htidocid=COD1AgHDudYAAAAAAAAAAA%3D%3D",
    job_highlights: {
      Qualifications: [
        "Translate advanced technology experience, an in-depth knowledge of the organizations tactical and strategic business objectives, the enterprise technological environment, the organization structure, and strategic technological opportunities and requirements into technical engineering solutions",
        "7+ years of Engineering experience, or equivalent demonstrated through one or a combination of the following: work experience, training, military experience, education",
        "7+ years of Java experience",
        "3+ years of experience in microservices development",
        "3+ years of experience with Cloud technologies",
      ],
      Responsibilities: [
        "As a Principal Java Engineer and passionate technologist, you will define the strategy and solutions to guide engineers in building innovative engineering accelerators and libraries to enable development and cloud adoption across the firm",
        "You will provide subject matter expertise, technology guidance, road maps, principles, standards, and best practices to support Group CIOs in managing their technology domains and meeting customer expectations",
        "As a key member of the team, your work will include designing and defining Modern Application frameworks and patterns",
        "Act as an advisor to leadership to influence adoption of modern engineering solutions, accelerators and practices to help address the complex needs of an enterprise application modernization and cloud adoption",
        "Collaborate with engineering and architecture to define the technology strategy; then take it to full execution",
        "Collaborate with engineering to design, develop, and deliver Core Frameworks that will be reused across Enterprise",
        "Provide vision, direction and expertise to leadership on implementing innovative and significant business solutions",
        "Maintain knowledge of industry best practices and new technologies and recommends innovations that enhance operations or provide a competitive advantage to the organization",
        "Strategically engage with all levels of professionals and managers across the enterprise and serve as an expert advisor to leadership",
        "Collaborate with vendor partners and Cloud Service Providers to effectively utilize the skills to help modernize applications",
      ],
      Benefits: [
        "The salary range for this role is $144,400 to $300,000 and is based on experience and qualifications",
        "Pay Range",
        "$144,400.00 - $300,000.00 Annual",
        "Information about Wells Fargo's employee benefits",
      ],
    },
  },
  {
    employer_name: "Lockheed Martin",
    employer_logo:
      "https://www.lockheedmartin.com/content/dam/lockheed-martin/general/lm-logo.svg",
    employer_website: "http://www.lockheedmartin.com",
    employer_company_type: "Manufacturing",
    job_publisher: "Salary.com",
    job_id: "w2oa7CXJ2zsAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title:
      "Senior Software Engineer - Java Focus (Security Clearance Required)",
    job_apply_link:
      "https://www.salary.com/job/lockheed-martin/senior-software-engineer-java-focus-security-clearance-required/j202303270327398885781",
    job_city: null,
    job_state: "CO",
    job_country: "US",
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=java&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=java&htidocid=w2oa7CXJ2zsAAAAAAAAAAA%3D%3D",
    job_highlights: {
      Qualifications: [
        "A successful candidate will have extensive Java experience with Object-Oriented programming experience, familiarity with Agile processes, and familiar with common industry tools such as Jira, Git, Gitlab, MATLAB, Eclipse, and JUnit tests",
        "Must hold an active TS/SCI security clearance",
        "Proficiency in Java and Object Oriented Programming (OOP)",
        "Experience with software unit testing",
        "Strong Math and/or Physics background",
        "Security Clearance Statement: This position requires a government security clearance, you must be a US Citizen for consideration",
      ],
      Responsibilities: [
        "This position will focus on the development, testing, and maintenance of custom Mission Analysis Software",
        "This software is a collection of tools used to model and simulate space-based RF payloads used in remote sensing applications to inform design decision by an adjacent architecture team",
        "The toolkit is developed by a small team that works closely with the users on regular basis to better understand tool use cases and requirements as well as assisting users in the usage of the tool",
        "This toolkit is used to help design the satellite systems of the future, enabling the Mission Analysis team to actively craft the future of Lockheed Martin business",
      ],
      Benefits: [
        "Our flexible schedules, competitive pay, and comprehensive benefits enable our employees to live a healthy, fulfilling life at and outside of work",
        "These condensed schedules provide employees with additional time away from the office and are in addition to our Paid Time off benefits",
      ],
    },
  },
  {
    employer_name: "Mobica",
    employer_logo: "https://m.iotone.com/files/vendor/mobica-limited_1.png",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "ixhkBo7bf_wAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "React Native Mobile Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/react-native-mobile-developer-at-mobica-3541973066",
    job_city: "Seattle",
    job_state: "WA",
    job_country: "US",
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+native&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+native&htidocid=ixhkBo7bf_wAAAAAAAAAAA%3D%3D",
    job_highlights: {
      Qualifications: [
        "3+ years of experience in React or React Native development",
        "Ability to dive into full-stack development if project gaps arise",
        "Dedication to quality, both in product quality and code quality",
        "B.S. degree in Computer Science or Electrical Engineering or equivalent experience",
        "Ability to be an on-site hybrid for this position in the Seattle area",
      ],
      Responsibilities: [
        "Plan and execute the development of React Native (iOS + Android) app features",
        "Develop full-stack mobile application features in a variety of languages, including but not limited to Javascript, Obj-C, Java, and PHP",
        "Contribute to the maintenance of existing internal and external app releases, including debugging code defects and adapting to the latest infrastructure",
        "Improve the consistency and quality of the internal app code base",
      ],
      Benefits: [
        "Competitive salary package",
        "Flexible working hours",
        "Opportunity to work from home",
        "Training and mentoring programs",
        "Ability to advance your technology skills",
        "Variety of projects with cutting edge technologies at the core",
        "Permanent employment",
      ],
    },
  },
  {
    employer_name: "Sabanto",
    employer_logo: null,
    employer_website: null,
    employer_company_type: null,
    job_publisher: "Sabanto",
    job_id: "WaV6CvGB5BQAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "React Native Full Stack Developer",
    job_apply_link:
      "https://sabanto.breezy.hr/p/6c4ee7a222b2-full-stack-react-native-developer",
    job_city: "Itasca",
    job_state: "IL",
    job_country: "US",
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+native&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+native&htidocid=WaV6CvGB5BQAAAAAAAAAAA%3D%3D",
    job_highlights: {
      Qualifications: [
        "Bachelor’s degree in Engineering, Computer Science, or equivalent work experience",
        "4+ years of professional experience with JavaScript, Node.js, React & React Native",
        "2+ years of professional experience building and running workloads in AWS",
        "Ability to understand business requirements and translate them into technical requirements",
        "Be a champion of Engineering best practices",
        "Familiarity with Git",
        "Familiarity with modern front-end CI/CD pipelines",
        "Excellent communication and interpersonal skills",
      ],
      Responsibilities: [
        "As our React Native Full Stack Engineer, you will be responsible for designing and building core apis, and user facing mobile applications powering our Autonomous Solutions",
        "You will also be entrusted to work with Product and Engineering to iterate over designs and ideas",
      ],
    },
  },
  {
    employer_name: "Ascension",
    employer_logo:
      "https://healthcare.ascension.org/-/media/project/ascension/healthcare/component-library/logos/ascension-logo.svg?iar=0&hash=4DF4E4D60C2D78C4FB7EFA852A610D26",
    employer_website: "http://www.ascensionhealth.org",
    employer_company_type: null,
    job_publisher: "Ascension Careers",
    job_id: "Ti_dVor94ioAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Sr. React Native Developer",
    job_apply_link: "https://jobs.ascension.org/jobs/254193?lang=en-us",
    job_city: "Chicago",
    job_state: "IL",
    job_country: "US",
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+native&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+native&htidocid=Ti_dVor94ioAAAAAAAAAAA%3D%3D",
    job_highlights: {
      Qualifications: [
        "B.S in Computer Science or equivalent experience",
        "3+ years of professional React Native development experience in an Agile environment",
        "Strong Computer Science fundamentals in OOAD, MVVM design patterns, data structures, and algorithms",
        "Strong experience on creating the React-Native modules (npm) for developing reusable custom libraries, components",
        "Strong experience in creating a Jenkins pipeline using third party tools like fastlane",
        "Good experience in deploying the applications on Apple AppStore and Google Playstores",
        "Proven experience developing in JavaScript and TypeScript languages",
        "Good foundation at working with third-party libraries (Redux, RxJS) and debugging dependency conflicts",
        "Strong understanding of mobile app development lifecycle",
        "Knowledge of object-oriented programming and reactive programming patterns",
        "Experience using RESTful APIs to integrate mobile applications to server side systems and an understanding of the document request model, and offline storage",
        "Experience with automated testing suites, like Jest or Mocha and postman, experience with unit and integration tests (Espresso, JUnit) and Co-routines",
        "Experience with dependency injection (Dagger)",
        "Ability to work as part of a large agile-driven software engineering effort, and a strong understanding of professional software engineering best practices for the full SDLC, including CI/CD",
        "Strong verbal and written communication skills",
        "Openness to new ideas and an unceasing desire to learn new things",
        "Outstanding interpersonal skills, a positive mindset, and a collaborative spirit",
        "High School diploma equivalency with 2 years of cumulative experience OR Associate's degree/Bachelor's degree with 1 year of experience OR 5 years of applicable cumulative job specific experience required",
      ],
      Responsibilities: [
        "Join Ascension as a fully remote Sr",
        "Our React Native developers will be asked to help with building performant mobile apps on both the iOS and Android platforms",
        "They will be responsible for architecting and building these applications, as well as coordinating with the teams responsible for other layers of the product infrastructure",
        "Develop high quality enterprise-scale React Native apps with pixel-perfect UIs across both Android and iOS mobile platforms",
        "Leverage native APIs for deep integrations with native mobile platforms",
        "Diagnose and fix bugs and performance bottlenecks for performance that feels native",
        "Maintain code and write automated tests to ensure the product is of the highest quality",
        "Break down complex requirements into independent coding tasks and strategies",
        "Create unit and integration tests to fully test and regress software",
        "Participate in design and code reviews",
        "Work with other teams (i.e",
        "Product, PM, etc.)",
        "to ensure delivered code meets specifications based on functional/technical specifications",
        "Participate in Agile routines and ceremonies; daily standups, sprint planning, sprint demos/retrospectives",
      ],
      Benefits: [
        "Paid time off (PTO)",
        "Various health insurance options & wellness plans",
        "Retirement benefits including employer match plans",
        "Long-term & short-term disability",
        "Employee assistance programs (EAP)",
        "Parental leave & adoption assistance",
        "Tuition reimbursement",
        "Ways to give back to your community",
        "In fact, Ascension spent nearly $46 million in tuition assistance alone to support associate growth and development",
      ],
    },
  },
  {
    employer_name: "Qbtech",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhgzW0Q6yxTCQ2iGOdytS27sPHsLOSEasj6Oes&s=0",
    employer_website: "http://www.qbtech.se",
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "35-ettW2fGkAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Senior Software Engineer, Backend (Java – Kotlin)",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/senior-software-engineer-backend-java-%E2%80%93-kotlin-at-qbtech-3549303652",
    job_city: "Houston",
    job_state: "TX",
    job_country: "US",
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=kotlin&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=kotlin&htidocid=35-ettW2fGkAAAAAAAAAAA%3D%3D",
    job_highlights: {
      Qualifications: [
        "Extensive development skills using Java and Kotlin",
        "Strong problem-solving mentality",
        "Knowledge of the Ktor framework",
        "Knowledge of at least one well known test framework such as Junit",
        "Good knowledge of network infrastructure related to web application (examples: load balancer, firewall, security groups, CDN etc.)",
        "Experience of working with service provisioning for at least one of the following cloud services platforms (AWS, Google Cloud, Microsoft Azure)",
        "Experience of an infrastructure as code (Terraform)",
        "Experience with containerised software (Docker)",
        "Experience from working with Agile development methodologies",
        "Excellent written and verbal skills",
        "At least 5 years documented experience",
        "Bachelor’s or Master’s degree in Computer Science or related field",
        "Fluent in English",
        "Legally eligible to work in the country of employment",
      ],
      Responsibilities: [
        "The role is based in Houston, Texas and will report to Director of Engineering based in Stockholm, Sweden",
        "Qbtech’s development of products and services are controlled by Qbtech Quality Management Systems, international standards and certificates as well as specific laws",
        "Develop and document new product features & stories",
        "Code reviews for peers",
        "Maintain and improve legacy code",
        "Manage DevOps and cloud infrastructure provisioning",
        "Manage software deployment",
        "Troubleshooting/investigation of incidents and bug fixing",
      ],
      Benefits: [
        "Strong, secure, yet flexible retirement benefits including a PERA Defined Benefit Plan or PERA Defined Contribution Plan www.copera.org plus 401(k) and 457 plans",
        "Medical and dental health plans",
        "Employer supplemented Health Savings Account",
        "Paid life insurance",
        "Short- and long-term disability coverage",
        "11 paid holidays per year plus vacation and sick leave",
        "BenefitHub state employee discount program",
        "Employee Wellness program MotivateMe",
        "Excellent work-life programs, such as flexible schedules, training and more",
      ],
    },
  },
  {
    employer_name: "iTech US, Inc.",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTroZHZPpgu7ecx2k4TTnMVpNytwAq8HFV-mkTq&s=0",
    employer_website: "http://www.itechus.com",
    employer_company_type: null,
    job_publisher: "Dice",
    job_id: "HCOp-BWqjMQAAAAAAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "Senior Android/Kotlin Developer",
    job_apply_link:
      "https://www.dice.com/job-detail/4bd7d16b-6513-41bb-86ad-5b2276ce3d6f",
    job_city: "Sunnyvale",
    job_state: "CA",
    job_country: "US",
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=kotlin&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=kotlin&htidocid=HCOp-BWqjMQAAAAAAAAAAA%3D%3D",
    job_highlights: {
      Qualifications: [
        "Experience with Android and Mobile software development using Kotlin",
        "Experience in unit and integration testing Android code",
        "Experience in design patterns, MVC, data structures and algorithms",
        "Experience with Google Play APIs: Maps, Location, and Cloud Messaging",
        "Experience using distributed source code version control systems (Git/GitHub), Agile, Scrum",
        "Experience with software debugging techniques (debuggers, loggers, crash report tools)",
        "Analyze memory issues such as memory leaks using memory analyzers tools (DDMS, MAT)",
        "Experience with embedded real time systems (memory and processing)",
        "Education: At least a Bachelor’s degree (or equivalent experience) in Computer Science, Software/Electronics Engineering, Information Systems, or a closely related field is required",
      ],
      Responsibilities: [
        "Execute Mobile Engineering projects - Participate in the discovery phase",
        "Participate in peer code reviews, and support the implementation of business solutions",
        "Troubleshoot business and production issues for Mobile devices",
      ],
    },
  },
  {
    employer_name: "American Express",
    employer_logo:
      "https://upload.wikimedia.org/wikipedia/commons/f/fa/American_Express_logo_%282018%29.svg",
    employer_website: "http://www.americanexpress.com",
    employer_company_type: "Retail",
    job_publisher: "Eightfold - Eightfold.ai",
    job_id: "AUguccxFnw8AAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Mobile Engineer - Swift / Java / Kotlin",
    job_apply_link:
      "https://aexp.eightfold.ai/careers/job/13457997-mobile-engineer-swift-java-kotlin-new-york-new-york-united-states?domain=aexp.com",
    job_city: "New York",
    job_state: "NY",
    job_country: "US",
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=kotlin&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=kotlin&htidocid=AUguccxFnw8AAAAAAAAAAA%3D%3D",
    job_highlights: {
      Qualifications: [
        "You should be familiar with modern software development methodologies and be able to dive deep and rapidly iterate on ideas despite ambiguity",
        "Business Product Knowledge",
        "Bachelor’s degree in Computer Science/Engineering/Mathematics or 1+ years of equivalent experience in related disciplines",
        "Excellent interpersonal and communication skills",
        "Knowledge of developing trends and emerging standards in mobile apps, mobile payments, and wearables",
        "Minimum of 1 year of experience in Mobile Development with IOS / Android and experience in Software Development",
        "Good understanding of RESTful APIs and how to connect applications to back-end services using asynchronous network calls",
        "Experience with Swift and/or Functional Programming",
        "Experience with Java and/or Kotlin (optional)",
      ],
      Responsibilities: [
        "Your primary responsibilities will be to work on a small team of engineers developing mobile products",
        "Taking your place as a core member of an agile team driving the latest development practices",
        "Writing code and unit tests, working with API specs and automation",
        "Identifying opportunities for adopting new technologies",
        "Join a team of engineers that delivers knowledge management solutions to businesses worldwide",
        "Contribute to the design, architecture, and development of apps that are elegant, efficient, secure, highly available, and maintainable",
        "Works closely with other developers and end users to ensure technical compatibility and user satisfaction",
        "Contribute insights into ways to improve our processes and tools",
        "Be highly motivated and maintain a positive, “can-do” attitude in a fast-moving environment",
        "Follow and help cultivate consistent development best practices",
        "Collaborates with project manager and other software developers to plan, design, develop, test, and maintain the application",
        "Provides thought-leadership regarding implementation best practices",
        "Assists in estimation and assessment of feasibility of features",
        "Foster a collaborative spirit across multiple teams",
        "Depending on role and business needs, colleagues will either work onsite, in a hybrid model (combination of in-office and virtual days) or fully virtually",
      ],
      Benefits: [
        "Salary Range: $70,000.00 to $135,000.00 annually + bonus + benefits",
      ],
    },
  },
];

export { dummyJobs };
